### ISSUE TITLE
Getting redirected to `http://localhost:3000/api/auth/error` when clicking Sign In

### ISSUE THREAD

**Issue by sergical** [HamedBahram/next-auth-demo#1]
First of all, thank you for the video and the demo code, trying to work this out for my app and getting the same error when pulling your repo and trying to make it work.

Updated `.env.local`
```
NEXTAUTH_SECRET="secret"
NEXTAUTH_URL="http://localhost:3000"
```

That's pretty much it (added my google provider key + secret as well)

https://github.com/HamedBahram/next-auth-demo/assets/3760543/fa94bf17-5040-4890-a433-30bb172e9b33

**Comment by MChiemelie** [comment]
Trying removing the quotation marks around the environmental variables. 
As in 

NEXTAUTH_SECRET=secret
NEXTAUTH_URL=http://localhost:3000

**Comment by HamedBahram** [comment]
> 

Hi Sergiy, try the following:

- Make sure you've renamed the `.env.example` to `.env.local` and provide your env variables
- Open up the dev tools and clear up all the `Cookies` and `Local Storage` under the Application tab

Let me know if this solves the problem.
