### ISSUE TITLE
vercel deployment not working.

### ISSUE THREAD

**Issue by sathishkannan162** [HamedBahram/next-auth-demo#2]
I was wondering whether you have stopped this deployment or there is a problem in deployment with vercel. When I visit the link: https://next-auth-demo-dun.vercel.app/. There is no demo app there.

**Comment by HamedBahram** [comment]
I reached the project limit of my tier in Vercel, and I might have deleted that project. Is there anything you wish to see in deployment?

**Comment by sathishkannan162** [comment]
Thank you so much. I really like your videos.
